// 5. Declare and initialize variables `leadCompanySize` as **String** 
String leadCompanySize = 'Medium' ; 
//     - checks if a Lead's Company size is either `Small` or `Medium`. 
if(leadCompanySize=='Small' || leadCompanySize=='Medium'){
//       - If either of these conditions are met, 
//         - print a message that says `Good Lead` 
    System.debug('Good Lead'); 
}
//       - else take no action 