// Task Set 1
// 2. Declare and initialize an **Integer** variable. 
Integer num = 77 ;
//    - checks if a given integer is **positive**, **negative**, or **zero**. 

//- If the num is **positive**, the program should print `Positive` 
if( num>0 ){
    System.debug('Positive'); 
//- If the num is **negative**, the program should print `negative`
}else if( num<0 ){
    System.debug('Negative');
//- Else print `Zero`
}else{
    System.debug('Zero');
}